# Generated by Django 4.1.7 on 2023-03-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_description_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='hi hello'),
            preserve_default=False,
        ),
    ]
