# Generated by Django 4.1.7 on 2023-03-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('newPage', models.BooleanField(verbose_name='Open in the new tab')),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
