# Generated by Django 4.1.7 on 2023-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_link_delete_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='portfolio/images')),
                ('headTag', models.CharField(max_length=20, verbose_name='Head Tag')),
            ],
        ),
    ]
